# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "89ca5a1ba0b892903cf433ba49fb5a26"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "test-app"
handle = "test-app-11014"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[build]
dev_store_url = "testssnowboards.myshopify.com"
